#
# Config for Supernatural (Bluray)
#

video:
  "*":
    codec: copy
    color_range: tv
    colorspace: bt709
    color_trc: bt709
    color_primaries: bt709
  "S0[1-5]*":
    codec: libx264
    crf: 18
    tune: film
    color_range: tv
    colorspace: bt709
    color_trc: bt709
    color_primaries: bt709
audio:
  "*":
    codec: copy
streams:
  "S0[1-2]*":
    # Audio
    - lang == "ger" && track == "001102"
    - lang == "eng" && track == "001100"
    # Subtitles
    - lang == "ger" && (track == "001203" || track == "001204")
    - lang == "eng" && track == "001201"
  "S03*":
    # Audio
    - lang == "ger" && track == "001101"
    - lang == "eng" && track == "001100"
    # Subtitles
    - lang == "ger" && track == "001204"
    - lang == "eng" && track == "001200"
  "S0[6-7]*":
    - lang == "ger" && track == "001102"
    - lang == "eng" && track == "001100"
    # Subtitles
    - lang == "ger" && track == "001202"
    - lang == "eng" && track == "001200"
