#
# Config for Supernatural (Bluray)
#

video:
  "*":
    codec: libx264
    crf: 18
    tune: film
    color_range: tv
    colorspace: bt709
    color_trc: bt709
    color_primaries: bt709
audio:
  "*":
    codec: copy
streams:
  "*":
    # Audio
    - lang == "ger" && track == "001102"
    - lang == "eng" && track == "001100"
    # Subtitles
    - lang == "ger" && (track == "001203" || track == "001204")
    - lang == "eng" && track == "001201"
